name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      
  deploy:
   runs-on: ubuntu-latest
   steps:
   - name: executing remote ssh commands using password
     uses: appleboy/ssh-action@master
     with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
             npm instal 
              npm install -g 
              cd ~/nodejs-demo-app
              start npm --name "api" -- run start
              git pull origin main
              npm install
              npm run build 
              pm2 restart api
